/*
 HTML5 Responsive Notify 2
 Version: 2.0.0
 (c) 2015 DMXzone.com
 @build 14-09-2015 13:03:40
*/
(function(e){function f(c){c.onclick=c.onClick;e.each(["onclick","onShown","onHidden"],function(f,e){"string"==typeof c[e]&&(c[e]=new Function(c[e]))});return c}e.dmxNotify=function(c){c=f(c);!e.dmxDataBindings||-1===c.title.indexOf("{{")&&-1===c.msg.indexOf("{{")||(-1!==c.title.indexOf("{{")&&(c.title=e.dmxDataBindings.$parseTemplate(c.title)),-1!==c.msg.indexOf("{{")&&(c.msg=e.dmxDataBindings.$parseTemplate(c.msg)));toastr.options=c;toastr[c.type||"success"](c.msg,c.title)};e.dmxNotify.closeAll=
function(){toastr.clear()}})(jQuery);
(function(e){e(["jquery"],function(f){return function(){function c(b,c){b||(b=m());g=f("#"+b.containerId);if(g.length)return g;if(c){var d=b;g=f("<div/>").attr("id",d.containerId).addClass(d.positionClass).attr("aria-live","polite").attr("role","alert");g.appendTo(f(d.target))}return g}function e(b,c,d){d=d&&d.force?d.force:!1;return b&&(d||0===f(":focus",b).length)?(b[c.hideMethod]({duration:c.hideDuration,easing:c.hideEasing,complete:function(){u(b)}}),!0):!1}function l(b){function e(a){null==a&&
(a="");return(new String(a)).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function d(){h.hover(l,C);!a.onclick&&a.tapToDismiss&&h.click(n);a.closeButton&&s&&s.click(function(a){a.stopPropagation?a.stopPropagation():void 0!==a.cancelBubble&&!0!==a.cancelBubble&&(a.cancelBubble=!0);n(!0)});a.onclick&&h.click(function(b){a.onclick(b);n()})}function n(b){var c=b&&!1!==a.closeMethod?a.closeMethod:a.hideMethod,d=b&&!1!==a.closeDuration?a.closeDuration:
a.hideDuration,e=b&&!1!==a.closeEasing?a.closeEasing:a.hideEasing;if(!f(":focus",h).length||b)return clearTimeout(k.intervalId),h[c]({duration:d,easing:e,complete:function(){u(h);if(a.onHidden&&"hidden"!==p.state)a.onHidden();p.state="hidden";p.endTime=new Date;r&&r(p)}})}function C(){if(0<a.timeOut||0<a.extendedTimeOut)v=setTimeout(n,a.extendedTimeOut),k.maxHideTime=parseFloat(a.extendedTimeOut),k.hideEta=(new Date).getTime()+k.maxHideTime}function l(){clearTimeout(v);k.hideEta=0;h.stop(!0,!0)[a.showMethod]({duration:a.showDuration,
easing:a.showEasing})}function t(){var a=(k.hideEta-(new Date).getTime())/k.maxHideTime*100;w.width(a+"%")}var a=m(),x=b.iconClass||a.iconClass;"undefined"!==typeof b.optionsOverride&&(a=f.extend(a,b.optionsOverride),x=b.optionsOverride.iconClass||x);var q;a:{if(a.preventDuplicates)if(b.message===y){q=!0;break a}else y=b.message;q=!1}if(!q){z++;g=c(a,!0);var v=null,h=f("<div/>");q=f("<div/>");var A=f("<div/>"),w=f("<div/>"),s=f(a.closeHtml),k={intervalId:null,hideEta:null,maxHideTime:null},p={toastId:z,
state:"visible",startTime:new Date,options:a,map:b};b.iconClass&&h.addClass(a.toastClass).addClass(x);b.title&&(q.append(a.escapeHtml?e(b.title):b.title).addClass(a.titleClass),h.append(q));b.message&&(A.append(a.escapeHtml?e(b.message):b.message).addClass(a.messageClass),h.append(A));a.closeButton&&(s.addClass("toast-close-button").attr("role","button"),h.prepend(s));a.progressBar&&(w.addClass("toast-progress"),h.prepend(w));a.newestOnTop?g.prepend(h):g.append(h);h.hide();h[a.showMethod]({duration:a.showDuration,
easing:a.showEasing,complete:a.onShown});0<a.timeOut&&(v=setTimeout(n,a.timeOut),k.maxHideTime=parseFloat(a.timeOut),k.hideEta=(new Date).getTime()+k.maxHideTime,a.progressBar&&(k.intervalId=setInterval(t,10)));d();r&&r(p);a.debug&&console&&console.log(p);return h}}function m(){return f.extend({},{tapToDismiss:!0,toastClass:"toast",containerId:"toast-container",debug:!1,showMethod:"fadeIn",showDuration:300,showEasing:"swing",onShown:void 0,hideMethod:"fadeOut",hideDuration:1E3,hideEasing:"swing",
onHidden:void 0,closeMethod:!1,closeDuration:!1,closeEasing:!1,extendedTimeOut:1E3,iconClasses:{error:"toast-error",info:"toast-info",success:"toast-success",warning:"toast-warning"},iconClass:"toast-info",positionClass:"toast-top-right",timeOut:5E3,titleClass:"toast-title",messageClass:"toast-message",escapeHtml:!1,target:"body",closeHtml:'<button type="button">&times;</button>',newestOnTop:!0,preventDuplicates:!1,progressBar:!1},t.options)}function u(b){g||(g=c());b.is(":visible")||(b.remove(),
0===g.children().length&&(g.remove(),y=void 0))}var g,r,z=0,t={clear:function(b,B){var d=m();g||c(d);if(!e(b,d,B))for(var n=g.children(),l=n.length-1;0<=l;l--)e(f(n[l]),d)},remove:function(b){var e=m();g||c(e);b&&0===f(":focus",b).length?u(b):g.children().length&&g.remove()},error:function(b,c,d){return l({type:"error",iconClass:m().iconClasses.error,message:b,optionsOverride:d,title:c})},getContainer:c,info:function(b,c,d){return l({type:"info",iconClass:m().iconClasses.info,message:b,optionsOverride:d,
title:c})},options:{},subscribe:function(b){r=b},success:function(b,c,d){return l({type:"success",iconClass:m().iconClasses.success,message:b,optionsOverride:d,title:c})},version:"2.1.2",warning:function(b,c,d){return l({type:"warning",iconClass:m().iconClasses.warning,message:b,optionsOverride:d,title:c})}},y;return t}()})})("function"===typeof define&&define.amd?define:function(e,f){"undefined"!==typeof module&&module.exports?module.exports=f(require("jquery")):window.toastr=f(window.jQuery)});
