/*
 DMXzone Responsive Text
 Version: 1.0.1
 (c) 2013 DMXzone.com
 @build 26-06-2013 15:18:29
*/
(function(c){var d={childSelector:">h1, >h2, >h3, >h4, >h5, >p, >div"};c.fn.dmxResponsiveText=function(n){this.bigtext(c.extend(!0,d,n));c(window).load(function(){c(window).trigger("resize")})}})(jQuery);
(function(c,d){function n(a,b,d,g,e,f){a.css(d,g+f);f=a.width();return f>=b?(a.css(d,""),f==b?{match:"exact",size:parseFloat((parseFloat(g)-0.1).toFixed(3))}:{match:"estimate",size:parseFloat((parseFloat(g)-e).toFixed(3))}):!1}var t=0,q=d("head"),u=c.BigText,v=d.fn.bigtext,b={DEFAULT_MIN_FONT_SIZE_PX:null,DEFAULT_MAX_FONT_SIZE_PX:528,GLOBAL_STYLE_ID:"bigtext-style",STYLE_ID:"bigtext-id",LINE_CLASS_PREFIX:"bigtext-line",EXEMPT_CLASS:"bigtext-exempt",DEFAULT_CHILD_SELECTOR:"> div",childSelectors:{div:"> div",
ol:"> li",ul:"> li"},noConflict:function(a){a&&(d.fn.bigtext=v,c.BigText=u);return b},init:function(){d("#"+b.GLOBAL_STYLE_ID).length||q.append(b.generateStyleTag(b.GLOBAL_STYLE_ID,[".bigtext * { white-space: nowrap; }",".bigtext ."+b.EXEMPT_CLASS+", .bigtext ."+b.EXEMPT_CLASS+" * { white-space: normal; }"]))},bindResize:function(a,b){d.throttle?d(c).unbind(a).bind(a,d.throttle(100,b)):(d.fn.smartresize&&(a="smartresize."+a),d(c).unbind(a).bind(a,b))},getStyleId:function(a){return b.STYLE_ID+"-"+
a},generateStyleTag:function(b,s){return d("<style>"+s.join("\n")+"</style>").attr("id",b)},clearCss:function(a){a=b.getStyleId(a);d("#"+a).remove()},generateCss:function(a,d,c,g){var e=[];b.clearCss(a);for(var f=0,j=d.length;f<j;f++)e.push("#"+a+" ."+b.LINE_CLASS_PREFIX+f+" {"+(g[f]?" white-space: normal;":"")+(d[f]?" font-size: "+d[f]+"px;":"")+(c[f]?" word-spacing: "+c[f]+"px;":"")+"}");return b.generateStyleTag(b.getStyleId(a),e)},jQueryMethod:function(a){b.init();a=d.extend({minfontsize:b.DEFAULT_MIN_FONT_SIZE_PX,
maxfontsize:b.DEFAULT_MAX_FONT_SIZE_PX,childSelector:"",resize:!0},a||{});return this.each(function(){var c=d(this).addClass("bigtext"),p=a.childSelector||b.childSelectors[this.tagName.toLowerCase()]||b.DEFAULT_CHILD_SELECTOR,g=c.width(),e=c.attr("id");e||(e="bigtext-id"+t++,c.attr("id",e));a.resize&&b.bindResize("resize.bigtext-event-"+e,function(){b.jQueryMethod.call(d("#"+e),a)});b.clearCss(e);c.find(p).addClass(function(a,d){return[d.replace(RegExp("\\b"+b.LINE_CLASS_PREFIX+"\\d+\\b"),""),b.LINE_CLASS_PREFIX+
a].join(" ")});var f=a.maxfontsize,j=a.minfontsize,c=c.clone(!0).addClass("bigtext-cloned").css({fontFamily:c.css("font-family"),"min-width":parseInt(g,10),width:"auto",position:"absolute",left:-9999,top:-9999}).appendTo(document.body),i=[],k=[],l=[],r=[];c.find(p).css({"float":"left",clear:"left"}).each(function(){var a=d(this),c=[4,1,0.4,0.1],e;if(a.hasClass(b.EXEMPT_CLASS)){i.push(null);r.push(null);l.push(false)}else{e=parseFloat(a.css("font-size"));e=(a.width()/e).toFixed(6);var h=parseFloat(((g-
20)/e).toFixed(3)),m=0,k=c.length;a:for(;m<k;m++){var o=1;b:for(;o<=4;o++){if(h+o*c[m]>f){h=f;break a}e=n(a,g,"font-size",h+o*c[m],c[m],"px");if(e!==false){h=e.size;if(e.match=="exact")break a;break b}}}r.push(g/h);if(h>f){i.push(f);l.push(false)}else if(j&&h<j){i.push(j);l.push(true)}else{i.push(h);l.push(false)}}}).each(function(a){var c=d(this),e=0;if(c.hasClass(b.EXEMPT_CLASS))k.push(null);else{c.css("font-size",i[a]+"px");for(var f=1;f<5;f=f+1){a=n(c,g,"word-spacing",f,1,"px");if(a!==false){e=
a.size;break}}c.css("font-size","");k.push(e)}}).removeAttr("style");c.remove();q.append(b.generateCss(e,i,k,l))})}};d.fn.bigtext=b.jQueryMethod;c.BigText=b})(this,jQuery);
