/*
 DMXzone Security Provider
 Version: 1.0.0
 (c) 2013 DMXzone.com
 @build 11-12-2013 12:24:08
*/
(function(a,l){function m(b,f){var i=a.Deferred();a.ajax({url:c.url,method:"post",data:a.extend(f,{action:b})}).done(function(a){a.identity?(n(a),i.resolve(a)):(n(),i.reject())}).fail(function(){n();i.reject()});return i.promise()}function g(a,f){c.events["on"+a]&&c.events["on"+a].call(null,f)}function n(a){a?p.setVariable("$SECURITY",a):p.removeVariable("$SECURITY")}if(a===l)alert("jQuery is required!");else if(a.dmxDataBindings===l)alert("HTML5 Data Bindings is required!");else{var p=a.dmxDataBindings,
j,k,d,e,o,h,c={url:null,form:{enabled:!1,name:"login",alert:".alert",username:"username",password:"password",remember:"remember"},modalRemember:!0,modalText:{title:"Enter your credentials",username:"Username",password:"Password",remember:"Remember Me",login:"Login",close:"Close",alert:"Invalid Username / Password"},events:{onValid:null,onInvalid:null,onLogin:null,onLoginFailed:null,onLogout:null,onModalShow:null,onModalShown:null,onModalHide:null,onModalHidden:null}};a.dmxSecurityProvider=function(b){a.extend(!0,
c,b);if(!c.url)throw"dmxSecurityProvider requires a valid url!";m("validate").done(function(a){g("Valid",a.identity)}).fail(function(){g("Invalid")});c.form.enabled&&a(document).ready(function(){a('[name="'+c.form.name+'"]').on("submit",function(f){f.preventDefault();a.dmxSecurityProvider.login(a(this).find('[name="'+c.form.username+'"]').val(),a(this).find('[name="'+c.form.password+'"]').val(),a(this).find('[name="'+c.form.remember+'"]').prop("checked")).done(function(){a(c.form.alert).hide()}).fail(function(){a(c.form.alert).show()})})});
a.each(c.events,function(a,b){"string"==typeof b&&(c.events[a]=function(a){return(new Function(b.replace(/##identity##/g,a))).call()})})};a.dmxSecurityProvider.modal=function(){var b=c.modalText;a.fn.modal===l?alert("Bootstrap Modal is required!"):(h||(h=a('<div class="modal fade"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button><h4 class="modal-title">'+b.title+'</h4></div><div class="modal-body"><div id="dmxAlert" class="alert alert-danger">'+
b.alert+'</div><div class="form-group control-group"><input class="form-control input-block-level" type="text" id="dmxUsername" placeholder="'+b.username+'"></div><div class="form-group control-group"><input class="form-control input-block-level" type="password" id="dmxPassword" placeholder="'+b.password+'"></div><div class="checkbox"><label><input id="dmxRemember" type="checkbox"> '+b.remember+'</label></div></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">'+b.close+
'</button> <button id="dmxLogin" class="btn btn-primary">'+b.login+"</button></div></div></div></div>").appendTo("body"),j=a("#dmxAlert"),k=a("#dmxLogin"),d=a("#dmxUsername"),e=a("#dmxPassword"),o=a("#dmxRemember"),h.on("shown.bs.modal",function(){d.focus()}),a("#dmxUsername,#dmxPassword").on("keyup",function(b){13==b.keyCode&&a("#dmxLogin").click()}),k.on("click",function(){var b=d.val(),c=e.val();o.prop("checked");!b||!c?(b||d.parent().addClass("error").addClass("has-error"),c||e.parent().addClass("error").addClass("has-error"),
b?e.focus():d.focus(),j.show()):(k.prop("disabled",!0),a.dmxSecurityProvider.login(d.val(),e.val(),o.prop("checked")).done(function(){h.modal("hide")}).fail(function(){j.show();d.focus()}).always(function(){k.prop("disabled",!1)}))})),j.hide(),d.parent().removeClass("error").removeClass("has-error"),e.parent().removeClass("error").removeClass("has-error"),h.modal("show"))};a.dmxSecurityProvider.login=function(a,c,d){return m("login",{username:a,password:c,remember:d?1:""}).done(function(a){g("Login",
a.identity)}).fail(function(){g("LoginFailed")})};a.dmxSecurityProvider.logout=function(){return m("logout").always(function(){g("Logout")})}}})(jQuery);
