/*
 DMXzone Lightbox
 Version: 2.0.0
 (c) 2014 DMXzone.com
 @build 04-12-2014 15:22:25
*/
DMX.Lightbox.plugins.flv={canHandleContent:function(){var a=DMX.Lightbox.instance.getCurrentConfig();return/(\.flv|\.m4v|\.f4v|\.f4p|\.f4a|\.f4b)(\?.*)?$/i.test(a.src)?50:0},invoke:function(){var a=DMX.Lightbox.instance,e=a.getCurrentConfig(),b=a.Viewer,h=b.jQuery;b.DMX.include("/dmx/widgets/flowplayer/flowplayer.min.js");h("body, html").css({overflow:"hidden",verticalAlign:"top"});var k=h('<div id="flvplayer" class="dmxLightboxFrameContent flash" />').css({width:"100%",height:"100%",verticalAlign:"top",
margin:0,top:0}).prependTo("body");a.setMetaData({keepAspect:!1,canBeOverlaped:!1});var l=a.isRunning;a.isRunning&&(a.runCommand("stopSlideshow"),a.isRunning=!0);var f=0,g=0,m=jQuery(".rounded",a.wrapper);a.addEventListener("loaderFinished.flvPlugin",function(){e.keyNavigation&&(a.runCommand("detachKeyEvents"),a.addEventListener("contentRemoved.flvPluginDekey",function(){a.runCommand("attachKeyEvents")},!0));m.offset();b.player=b.flowplayer(k[0],DMX.toAbsolutePath("/dmx/widgets/flowplayer/flowplayer.swf"),
{clip:{url:DMX.toAbsolutePath(e.src),autoPlay:!0,scaling:"scale",autoBuffering:!0,onStart:function(d){var c=!1;f||(f=d.metaData.width||d.width||400,a.setMetaData({width:f}),c=!0);g||(g=d.metaData.height||d.height-28||300,a.setMetaData({height:g}),c=!0);c&&(d=f,c=g,b.player.pause(),a.setMetaData({keepAspect:!0}),a.runCommand("resizeTo",d,c,function(){a.runCommand("setTitle",a.getTitle());b.player.getClip().autoPlay&&b.player.play()}))}},onFinish:function(){setTimeout(function(){b&&b.player&&!b.player.isPlaying()&&
(a.dispatch("loaderFinished"),l&&a.isRunning&&(a.isRunning=!1,a.runCommand("startSlideshow")))},1E3)},onError:function(b,c){a.error("Flowplayer returned error "+b+': "'+c+'"')},plugins:{controls:{autoHide:"always",top:"100%",bottom:0}}})},!0);a.errorMessage='The content at "'+e.src+'" could not be loaded for '+e.contentLoadTimeout+" seconds.";a.Viewer.showContent(k,!0,!0,null,null,null,null,1)}};
