/*
 DMXzone Database Updater
 Version: 1.1.0
 (c) 2013 DMXzone.com
 @build 03-12-2013 10:13:37
*/
(function(d,h){function g(a,b){return a instanceof b}if(d===h)alert("jQuery is required!");else{var e=d.dmxDataBindings,f=function(a){if(!(this instanceof f))return new f(a);a.id&&(f.databaseActions[a.id]=this);this.init(a)};f.databaseActions={};f.get=function(a){return f.databaseActions[a]};f.prototype={init:function(a){this.cfg=d.extend({alertError:!0},a);this.state();if(a.form)d("[name="+a.form+"]").on("submit",function(){this.send()})},run:function(a,b){return this.send(a,b)},send:function(a,
b){function f(){this.runCallback(c.complete);d(this).trigger("complete")}function j(a){this.state({state:{success:!0},data:a});this.runCallback(c.success,[a]);d(this).trigger("success",[a])}function h(a,b,e){if(/json/.test(a.getResponseHeader("Content-Type"))){var f=d.parseJSON(a.responseText);f.message&&(e=f.message)}401==a.status?(this.state({state:{unauthorized:!0}}),this.runCallback(c.unauthorized,[b,e])):402==a.status?(this.state({state:{forbidden:!0}}),this.runCallback(c.forbidden,[b,e])):(this.state({state:{error:!0},
error:{status:b,message:e}}),this.runCallback(c.error,[b,e]));c.alertError&&alert(e);d(this).trigger("error",[b,e])}var i=d.Event("beforeSend"),c=d.extend(!0,{},this.cfg);a&&("string"==typeof a?c.url=a:d.isPlainObject(a)?d.extend(!0,c,a):g(a,e.Scope)?b=a:g(a,jQuery)?b=e.Scope.closest(a[0]):g(a,Element)?b=e.Scope.closest(a):g(a,d.Event)||g(a,Event)?b=e.Scope.closest(a.target):console&&console.error("Invalid argument for send()",a));g(b,Element)&&(b=g(b,e.Scope)?b:e.Scope.closest(b));g(b,e.Scope)||
(b=e.globalScope);"string"==typeof c.beforeSend&&(c.beforeSend=new Function("settings",this.parse(c.beforeSend,b)));"string"==typeof c.complete&&(c.complete=new Function(this.parse(c.complete,b)));"string"==typeof c.error&&(c.error=new Function("textStatus","errorThrown",this.parse(c.error,b)));"string"==typeof c.unauthorized&&(c.unauthorized=new Function("textStatus","errorThrown",this.parse(c.unauthorized,b)));"string"==typeof c.forbidden&&(c.forbidden=new Function("textStatus","errorThrown",this.parse(c.forbidden,
b)));"string"==typeof c.success&&(c.success=new Function("data",this.parse(c.success,b)));!1!==this.runCallback(c.beforeSend,[c])&&(d(this).trigger(i,[c]),i.isDefaultPrevented()||(this.state({state:{executing:!0}}),this.abort(),d.ajax(this.parse(c.url,b),{type:"POST",async:c.async,data:this.parse(c.data,b),dataType:c.dataType,statusCode:c.statusCode||{}}).done(d.proxy(j,this)).fail(d.proxy(h,this)).always(d.proxy(f,this))))},abort:function(){this.xhr&&this.xhr.abort&&(this.xhr.abort(),this.state())},
parse:function(a,b){if(e===h)return a;if("string"==typeof a){var f;return(f=/\{\{(.+?)\}\}/.exec(a))&&f[0]==a?e.$parse(a,b):e.$parseTemplate(a,b)}if(d.isPlainObject(a)||d.isArray(a))for(var g in a)a[g]=this.parse(a[g],b);return a},runCallback:function(a,b){try{return a.apply(this,b)}catch(d){}},state:function(a){this.cfg.id&&e&&e.setVariable(this.cfg.id,d.extend({state:{executing:!1,success:!1,error:!1,unauthorized:!1,forbidden:!1},data:null,error:null},a))}};d.dmxDatabaseAction=f}})(jQuery);
