/*
 HTML5 Responsive Notify
 Version: 1.0.1
 (c) 2013 DMXzone.com
 @build 05-07-2013 16:38:31
*/
(function(e){e.dmxNotify=function(d){var g=d;g.onclick=g.onClick;e.each(["onclick","onFadeIn","onFadeOut"],function(e,d){"string"==typeof g[d]&&(g[d]=new Function(g[d]))});d=g;toastr.options=d;toastr[d.type||"success"](d.msg,d.title)};e.dmxNotify.closeAll=function(){toastr.clear()}})(jQuery);
(function(e){function d(a){function l(){if(!(0<e(":focus",f).length))return f.fadeOut(b.fadeOut,function(){n(f);if(b.onFadeOut)b.onFadeOut();i.state="hidden";i.endTime=new Date;j&&j(i)})}var b=h(),d=a.iconClass||b.iconClass;"undefined"!==typeof a.optionsOverride&&(b=e.extend(b,a.optionsOverride),d=a.optionsOverride.iconClass||d);o++;c=g(b);var m=null,f=e("<div/>"),k=e("<div/>"),p=e("<div/>"),i={toastId:o,state:"visible",startTime:new Date,options:b,map:a};a.iconClass&&f.addClass(b.toastClass).addClass(d);
a.title&&(k.append(a.title).addClass(b.titleClass),f.append(k));a.message&&(p.append(a.message).addClass(b.messageClass),f.append(p));f.hide();b.newestOnTop?c.prepend(f):c.append(f);f.fadeIn(b.fadeIn,b.onFadeIn);0<b.timeOut&&(m=setTimeout(l,b.timeOut));f.hover(function(){clearTimeout(m);f.stop(true,true).fadeIn(b.fadeIn)},function(){if(b.timeOut>0||b.extendedTimeOut>0)m=setTimeout(l,b.extendedTimeOut)});!b.onclick&&b.tapToDismiss&&f.click(l);b.onclick&&f.click(function(){b.onclick()&&l()});j&&j(i);
b.debug&&console&&console.log(i);return f}function g(a){a||(a=h());c=e("#"+a.containerId);if(c.length)return c;c=e("<div/>").attr("id",a.containerId).addClass(a.positionClass);c.appendTo(e(a.target));return c}function h(){return e.extend({},q,k.options)}function n(a){c||(c=g());a.is(":visible")||(a.remove(),0===c.children().length&&c.remove())}var c,j,o=0,q={tapToDismiss:!0,toastClass:"toast",containerId:"toast-container",debug:!1,fadeIn:300,onFadeIn:void 0,fadeOut:1E3,onFadeOut:void 0,extendedTimeOut:1E3,
iconClasses:{error:"toast-error",info:"toast-info",success:"toast-success",warning:"toast-warning"},iconClass:"toast-info",positionClass:"toast-top-right",timeOut:5E3,titleClass:"toast-title",messageClass:"toast-message",target:"body",newestOnTop:!0},k={clear:function(a){var d=h();c||g(d);a&&0===e(":focus",a).length?a.fadeOut(d.fadeOut,function(){n(a)}):c.children().length&&c.fadeOut(d.fadeOut,function(){c.remove()})},error:function(a,c,b){return d({type:"error",iconClass:h().iconClasses.error,message:a,
optionsOverride:b,title:c})},getContainer:g,info:function(a,c,b){return d({type:"info",iconClass:h().iconClasses.info,message:a,optionsOverride:b,title:c})},options:{},subscribe:function(a){j=a},success:function(a,c,b){return d({type:"success",iconClass:h().iconClasses.success,message:a,optionsOverride:b,title:c})},version:"1.3.1",warning:function(a,c,b){return d({type:"warning",iconClass:h().iconClasses.warning,message:a,optionsOverride:b,title:c})}};return window.toastr=k})(jQuery);
