<?php
$base = realpath(dirname(__FILE__)) . '/';
require($base.'../dmxConnections/xampp_local.php');
require_once($base.'../ScriptLibrary/dmxDatabaseConnector/sqlBuilder.php');
require_once($base.'../ScriptLibrary/dmxDatabaseConnector/adapters/mysql/sqlBuilder.php');

$cfg = <<<JSON
{"type": "select", "table": "tournament_game_player", "columns": [{"table": "tournament_game_player", "column": "tourney_game_player_id", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "game_result", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "game_points", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "mission_points", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "total_points", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "results_approved", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "player_id", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "player_handle", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "tourney_round_id", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "tourney_round_title", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "tournament_id", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "game_id", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "game_title", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "Game_session", "alias": "", "sortable": false}, {"table": "tournament_game_player", "column": "table_id", "alias": "", "sortable": false}], "wheres": [{"table": "tournament_game_player", "column": "tourney_round_id", "bool": "and", "operator": "=", "value": {"from": "url", "value": "rd", "required": true, "default": ""}}, {"table": "tournament_game_player", "column": "tournament_id", "bool": "and", "operator": "=", "value": {"from": "url", "value": "tourney", "required": true, "default": ""}}], "orders": [{"table": "tournament_game_player", "column": "table_id", "direction": "ASC"}, {"table": "tournament_game_player", "column": "total_points", "direction": "DESC"}], "joins": []}
JSON;

$conn = new SqlConnection();
$conn->execute(SqlBuilder($cfg), TRUE);
?>