/*
 DMXzone Uniform
 Version: 1.0.2
 (c) 2013 DMXzone.com
 @build 20-06-2013 13:26:45
*/
(function(f){f.fn.dmxUniform=function(l){l.doNotChange?f(this.selector).find("input, select, textarea, button").not(l.doNotChange).uniform(l):f(this.selector).find("input, select, textarea, button").uniform(l)}})(jQuery);
(function(f,l){function h(a){var b=Array.prototype.slice.call(arguments,1);return a.prop?a.prop.apply(a,b):a.attr.apply(a,b)}function i(a,b,c){var d,e;for(d in c)c.hasOwnProperty(d)&&(e=d.replace(/ |$/g,b.eventNamespace),a.bind(e,c[d]))}function j(a,b,c){i(a,c,{focus:function(){b.addClass(c.focusClass)},blur:function(){b.removeClass(c.focusClass);b.removeClass(c.activeClass)},mouseenter:function(){b.addClass(c.hoverClass)},mouseleave:function(){b.removeClass(c.hoverClass);b.removeClass(c.activeClass)},
"mousedown touchbegin":function(){a.is(":disabled")||b.addClass(c.activeClass)},"mouseup touchend":function(){b.removeClass(c.activeClass)}})}function n(a,b){a.removeClass(b.hoverClass+" "+b.focusClass+" "+b.activeClass)}function o(a,b,c){var d=b.is(":checked");b.prop?b.prop("checked",d):d?b.attr("checked","checked"):b.removeAttr("checked");b=c.checkedClass;d?a.addClass(b):a.removeClass(b)}function m(a,b,c){c=c.disabledClass;b.is(":disabled")?a.addClass(c):a.removeClass(c)}function r(a,b,c){switch(c){case "after":return a.after(b),
a.next();case "before":return a.before(b),a.prev();case "wrap":return a.wrap(b),a.parent()}return null}function p(a,b,c){var d,e,g;c||(c={});c=f.extend({bind:{},divClass:null,divWrap:"wrap",spanClass:null,spanHtml:null,spanWrap:"wrap"},c);d=f("<div />");e=f("<span />");b.autoHide&&(a.is(":hidden")&&"none"===a.css("display"))&&d.hide();c.divClass&&d.addClass(c.divClass);b.wrapperClass&&d.addClass(b.wrapperClass);c.spanClass&&e.addClass(c.spanClass);g=h(a,"id");b.useID&&g&&h(d,"id",b.idPrefix+"-"+g);
c.spanHtml&&e.html(c.spanHtml);d=r(a,d,c.divWrap);e=r(a,e,c.spanWrap);m(d,a,b);return{div:d,span:e}}function u(a,b){var c;if(!b.wrapperClass)return null;c=f("<span />").addClass(b.wrapperClass);return c=r(a,c,"wrap")}function w(a){if(a[0].multiple)return!0;a=h(a,"size");return!a||1>=a?!1:!0}function s(){return!1}function t(a,b){i(a,b,{"selectstart dragstart mousedown":s});a.css({MozUserSelect:"none",msUserSelect:"none",webkitUserSelect:"none",userSelect:"none"})}function x(a,b,c){a=a.val();""===a?
a=c.fileDefaultHtml:(a=a.split(/[\/\\]+/),a=a[a.length-1]);b.text(a)}function y(a,b,c){var d;d=[];a.each(function(){for(var a in b)Object.prototype.hasOwnProperty.call(b,a)&&(d.push({el:this,name:a,old:this.style[a]}),this.style[a]=b[a])});for(c();d.length;)a=d.pop(),a.el.style[a.name]=a.old}function z(a,b){var c;c=a.parents();c.push(a[0]);c=c.not(":visible");y(c,{visibility:"hidden",display:"block",position:"absolute"},b)}function A(a,b){return function(){a.unwrap().unwrap().unbind(b.eventNamespace)}}
var v=!0,B=!1,C=[{match:function(a){return a.is("a, button, :submit, :reset, input[type='button']")},apply:function(a,b){var c,d,e,g,k;d=b.submitDefaultHtml;a.is(":reset")&&(d=b.resetDefaultHtml);g=a.is("a, button")?function(){return a.html()||d}:function(){var b;b=(b=h(a,"value"))?f("<span />").text(b).html():"";return b||d};e=p(a,b,{divClass:b.buttonClass,spanHtml:g()});c=e.div;j(a,c,b);k=!1;i(c,b,{"click touchend":function(){var b,c;if(!k&&!a.is(":disabled")){k=true;if(a[0].dispatchEvent){b=document.createEvent("MouseEvents");
b.initEvent("click",true,true);b=a[0].dispatchEvent(b);if(a.is("a")&&b){b=h(a,"target");c=h(a,"href");!b||b==="_self"?document.location.href=c:window.open(c,b)}}else a.click();k=false}}});t(c,b);return{remove:function(){c.after(a);c.remove();a.unbind(b.eventNamespace);return a},update:function(){n(c,b);m(c,a,b);a.detach();e.span.html(g()).append(a)}}}},{match:function(a){return a.is(":checkbox")},apply:function(a,b){var c,d,e;c=p(a,b,{divClass:b.checkboxClass});d=c.div;e=c.span;j(a,d,b);i(a,b,{"click touchend":function(){o(e,
a,b)}});o(e,a,b);return{remove:A(a,b),update:function(){n(d,b);e.removeClass(b.checkedClass);o(e,a,b);m(d,a,b)}}}},{match:function(a){return a.is(":file")},apply:function(a,b){function c(){x(a,g,b)}var d,e,g,k;d=p(a,b,{divClass:b.fileClass,spanClass:b.fileButtonClass,spanHtml:b.fileButtonHtml,spanWrap:"after"});e=d.div;k=d.span;g=f("<span />").html(b.fileDefaultHtml);g.addClass(b.filenameClass);g=r(a,g,"after");h(a,"size")||h(a,"size",e.width()/10);j(a,e,b);c();navigator.cpuClass&&!navigator.product?
i(a,b,{click:function(){a.trigger("change");setTimeout(c,0)}}):i(a,b,{change:c});t(g,b);t(k,b);return{remove:function(){g.remove();k.remove();return a.unwrap().unbind(b.eventNamespace)},update:function(){n(e,b);x(a,g,b);m(e,a,b)}}}},{match:function(a){return a.is("input")?(a=(" "+h(a,"type")+" ").toLowerCase(),0<=" color date datetime datetime-local email month number password search tel text time url week ".indexOf(a)):!1},apply:function(a,b){var c,d;c=h(a,"type");a.addClass(b.inputClass);d=u(a,
b);j(a,a,b);b.inputAddTypeAsClass&&a.addClass(c);return{remove:function(){a.removeClass(b.inputClass);b.inputAddTypeAsClass&&a.removeClass(c);d&&a.unwrap()},update:s}}},{match:function(a){return a.is(":radio")},apply:function(a,b){var c,d,e;c=p(a,b,{divClass:b.radioClass});d=c.div;e=c.span;j(a,d,b);i(a,b,{"click touchend":function(){f.uniform.update(f(':radio[name="'+h(a,"name")+'"]'))}});o(e,a,b);return{remove:A(a,b),update:function(){n(d,b);o(e,a,b);m(d,a,b)}}}},{match:function(a){return a.is("select")&&
!w(a)?!0:!1},apply:function(a,b){var c,d,e,g;b.selectAutoWidth&&z(a,function(){g=a.width()});c=p(a,b,{divClass:b.selectClass,spanHtml:(a.find(":selected:first")||a.find("option:first")).html(),spanWrap:"before"});d=c.div;e=c.span;b.selectAutoWidth?z(a,function(){y(f([e[0],d[0]]),{display:"block"},function(){var a;a=e.outerWidth()-e.width();d.width(g+a);e.width(g)})}):d.addClass("fixedWidth");j(a,d,b);i(a,b,{change:function(){e.html(a.find(":selected").html());d.removeClass(b.activeClass)},"click touchend":function(){var b=
a.find(":selected").html();e.html()!==b&&a.trigger("change")},keyup:function(){e.html(a.find(":selected").html())}});t(e,b);return{remove:function(){e.remove();a.unwrap().unbind(b.eventNamespace);return a},update:function(){b.selectAutoWidth?(f.uniform.restore(a),a.uniform(b)):(n(d,b),e.html(a.find(":selected").html()),m(d,a,b))}}}},{match:function(a){return a.is("select")&&w(a)?!0:!1},apply:function(a,b){var c;a.addClass(b.selectMultiClass);c=u(a,b);j(a,a,b);return{remove:function(){a.removeClass(b.selectMultiClass);
c&&a.unwrap()},update:s}}},{match:function(a){return a.is("textarea")},apply:function(a,b){var c;a.addClass(b.textareaClass);c=u(a,b);j(a,a,b);return{remove:function(){a.removeClass(b.textareaClass);c&&a.unwrap()},update:s}}}],q;if(q=navigator.cpuClass&&!navigator.product)q="undefined"!==typeof window.XMLHttpRequest?!0:!1,q=!q;q&&(v=!1);f.uniform={defaults:{activeClass:"active",autoHide:!0,buttonClass:"button",checkboxClass:"checker",checkedClass:"checked",disabledClass:"disabled",eventNamespace:".uniform",
fileButtonClass:"action",fileButtonHtml:"Choose File",fileClass:"uploader",fileDefaultHtml:"No file selected",filenameClass:"filename",focusClass:"focus",hoverClass:"hover",idPrefix:"uniform",inputAddTypeAsClass:!0,inputClass:"uniform-input",radioClass:"radio",resetDefaultHtml:"Reset",resetSelector:!1,selectAutoWidth:!0,selectClass:"selector",selectMultiClass:"uniform-multiselect",submitDefaultHtml:"Submit",textareaClass:"uniform",useID:!0,wrapperClass:null},elements:[]};f.fn.uniform=function(a){var b=
this,a=f.extend({},f.uniform.defaults,a);if(!B){B=!0;var c,d;d=f('<div style="width:0;height:0;color:rgb(120,2,153)">');f("body").append(d);c=d.get(0);c=window.getComputedStyle?window.getComputedStyle(c,"").color:(c.currentStyle||c.style||{}).color;d.remove();"rgb(120,2,153)"!==c.replace(/ /g,"")&&(v=!1)}if(!v)return this;a.resetSelector&&f(a.resetSelector).mouseup(function(){window.setTimeout(function(){f.uniform.update(b)},10)});return this.each(function(){var b=f(this),c,d;if(b.data("uniformed"))f.uniform.update(b);
else for(c=0;c<C.length;c+=1)if(d=C[c],d.match(b,a)){c=d.apply(b,a);b.data("uniformed",c);f.uniform.elements.push(b.get(0));break}})};f.uniform.restore=f.fn.uniform.restore=function(a){a===l&&(a=f.uniform.elements);f(a).each(function(){var a=f(this),c;if(c=a.data("uniformed")){c.remove();c=f.inArray(this,f.uniform.elements);c>=0&&f.uniform.elements.splice(c,1);a.removeData("uniformed")}})};f.uniform.update=f.fn.uniform.update=function(a){a===l&&(a=f.uniform.elements);f(a).each(function(){var a=f(this),
c;(c=a.data("uniformed"))&&c.update(a,c.options)})}})(jQuery);
