function getAllDMXLightboxPresets() {
	return {
		blue        :{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#001a40", overlayOpacity:0.75, radius:47, bgColor:"#004080", borderWidth:4, borderColor:"#a4d1ff", paddingColor:"#2f5793", padding:1 , bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#c4e1ff", pauseTime:5, easing:"easeOutCirc", innerBorderWidth:1, innerBorderColor:"#003264", innerBorderStyle:"groove", debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true},
		'border-art':{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#000"   , overlayOpacity:0.75, radius:6 , bgColor:"#949494", borderWidth:1, borderColor:"#FFF"   , paddingColor:"#363636", padding:2 , bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#DDD"   , pauseTime:5, easing:"easeOutCirc", innerBorderWidth:3, innerBorderColor:"#242424", innerBorderStyle:"double", debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true},
		classic     :{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#000"   , overlayOpacity:0.75, radius:46, bgColor:"#fff"   , borderWidth:0, borderColor:"#9e9e9e", paddingColor:"#000"   , padding:0 , bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#000"   , pauseTime:5, easing:"easeOutCirc", innerBorderWidth:3, innerBorderColor:"#333"   , innerBorderStyle:"solid" , debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true},
		'default'   :{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#000"   , overlayOpacity:0.75, radius:46, bgColor:"#383838", borderWidth:4, borderColor:"#FFF"   , paddingColor:"#000"   , padding:1 , bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#DDD"   , pauseTime:5, easing:"easeOutCirc", innerBorderWidth:1, innerBorderColor:"#474747", innerBorderStyle:"solid" , debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true},
		minimalistic:{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#000"   , overlayOpacity:0.75, radius:0 , bgColor:"#000"   , borderWidth:1, borderColor:"#FFF"   , paddingColor:"#000"   , padding:0 , bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#DDD"   , pauseTime:5, easing:"easeOutCirc", innerBorderWidth:0, innerBorderColor:"#333"   , innerBorderStyle:"double", debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true},
		orange      :{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#953100", overlayOpacity:0.9 , radius:8 , bgColor:"#ce2f00", borderWidth:1, borderColor:"#ff8040", paddingColor:"#a82411", padding:4 , bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#ffa"   , pauseTime:5, easing:"easeOutCirc", innerBorderWidth:4, innerBorderColor:"#800000", innerBorderStyle:"double", debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true},
		paspartu    :{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#c0c0c0", overlayOpacity:0.75, radius:50, bgColor:"#fff"   , borderWidth:2, borderColor:"#808080", paddingColor:"#c0c0c0", padding:16, bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#595959", pauseTime:5, easing:"easeOutCirc", innerBorderWidth:3, innerBorderColor:"#a3a3a3", innerBorderStyle:"double", debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true},
		thin        :{showTime:500, slideTime:5000, transitionTime:500, overlayColor:"#000"   , overlayOpacity:0.75, radius:3 , bgColor:"#c0c0c0", borderWidth:1, borderColor:"#fff"   , paddingColor:"#c0c0c0", padding:1 , bottomBarTopOffset:5, TopBarBottomOffset:5, titleMaxLength:"auto", dragable:true, useTitle:true, useStatusbar:true, fixPNG:true, noContextMenu:true, noImageToolbar:true, hideSelects:true, keyNavigation:true, color:"#fff"   , pauseTime:5, easing:"easeOutCirc", innerBorderWidth:1, innerBorderColor:"#808080", innerBorderStyle:"solid" , debugMode:false, contentLoadTimeout:20, displayErrors:true, showCloseButton:true, showPrefsButton:true, closeOnOverlayClick:true, showAboutButton:true}
	};
}